version: 2.1

global-variables: &global-variables
  BLOCKCHAIN_NAME: bsc

jobs:
  build-and-upload:
    working_directory: /build
    docker:
      - image: xozzslip/ubuntu-go
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: '.'
      - run:
          name: Go Build & Publish
          environment:
            <<: *global-variables
          command: |
            VERSION=$(git log --decorate --pretty=oneline @ | egrep 'tag: v[A-Za-z0-9\.-]+' -o | cut -d ":" -f2 | head -1 | sed -e 's/^ *//')
            make geth
            scp ./build/bin/geth root@65.108.15.182:/mnt/chaindata/$BLOCKCHAIN_NAME/bin/geth-$VERSION-$CIRCLE_SHA1
            cd ..
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

workflows:
  build:
    jobs:
      - build-and-upload:
          filters:
            branches:
              only: feature/full-block-api
